spring:
  application:
    name: vyaly_buhgalter

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:buhgalter}
    username: ${POSTGRES_USER:buhgalter}
    password: ${POSTGRES_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: vyaly_buhgalter_bot

logging:
  level:
    ru.vyaly_buhgalter: DEBUG
